compilation:
  cloud_properties:
    availability_zone: us-west-2a
    instance_type: c4.large
  network: vault_z1
  reuse_compilation_vms: true
  workers: 1
director_uuid: 606af3cd-790d-4752-88f2-c1db92732102
disk_pools: []
jobs:
- instances: 1
  name: vault_z1
  networks:
  - name: vault_z1
    static_ips:
    - 10.4.1.16
  persistent_disk: 4096
  properties:
    consul:
      join_hosts:
      - 10.4.1.16
      - 10.4.2.16
      - 10.4.3.16
    vault:
      backend:
        use_consul: true
  resource_pool: small_z1
  templates:
  - name: vault
    release: vault
  - name: consul
    release: consul
- instances: 1
  name: vault_z2
  networks:
  - name: vault_z2
    static_ips:
    - 10.4.2.16
  persistent_disk: 4096
  properties:
    consul:
      join_hosts:
      - 10.4.1.16
      - 10.4.2.16
      - 10.4.3.16
    vault:
      backend:
        use_consul: true
  resource_pool: small_z2
  templates:
  - name: vault
    release: vault
  - name: consul
    release: consul
- instances: 1
  name: vault_z3
  networks:
  - name: vault_z3
    static_ips:
    - 10.4.3.16
  persistent_disk: 4096
  properties:
    consul:
      join_hosts:
      - 10.4.1.16
      - 10.4.2.16
      - 10.4.3.16
    vault:
      backend:
        use_consul: true
  resource_pool: small_z3
  templates:
  - name: vault
    release: vault
  - name: consul
    release: consul
name: aws-proto-vault
networks:
- name: vault_z1
  subnets:
  - cloud_properties:
      security_groups:
      - wide-open
      subnet: subnet-10f36466
    dns:
    - 10.4.0.2
    gateway: 10.4.1.1
    range: 10.4.1.0/24
    reserved:
    - 10.4.1.2 - 10.4.1.3
    - 10.4.1.4 - 10.4.1.15
    - 10.4.1.32 - 10.4.1.254
    static:
    - 10.4.1.16 - 10.4.1.18
  type: manual
- name: vault_z2
  subnets:
  - cloud_properties:
      security_groups:
      - wide-open
      subnet: subnet-6d84f809
    dns:
    - 10.4.2.2
    gateway: 10.4.2.1
    range: 10.4.2.0/24
    reserved:
    - 10.4.2.2 - 10.4.2.3
    - 10.4.2.4 - 10.4.2.15
    - 10.4.2.32 - 10.4.2.254
    static:
    - 10.4.2.16 - 10.4.2.18
  type: manual
- name: vault_z3
  subnets:
  - cloud_properties:
      security_groups:
      - wide-open
      subnet: subnet-03409d5b
    dns:
    - 10.4.3.2
    gateway: 10.4.3.1
    range: 10.4.3.0/24
    reserved:
    - 10.4.3.2 - 10.4.3.3
    - 10.4.3.4 - 10.4.3.15
    - 10.4.3.32 - 10.4.3.254
    static:
    - 10.4.3.16 - 10.4.3.18
  type: manual
properties:
  vault:
    ha:
      domain: 10.4.1.16
    listener:
      tcp:
        tls:
          certificate: REDACTED
          key: REDACTED
releases:
- name: consul
  sha1: 9a0591c6b4d88d7d756ea933e14ddf112d05f334
  url: https://bosh.io/d/github.com/cloudfoundry-community/consul-boshrelease?v=20
  version: 20
- name: vault
  sha1: 1e44414639cfec645b2a6463f2aad2573752e65f
  url: https://bosh.io/d/github.com/cloudfoundry-community/vault-boshrelease?v=0.4.1
  version: 0.4.1
resource_pools:
- cloud_properties:
    availability_zone: us-west-2a
    instance_type: m3.medium
  name: small_z1
  network: vault_z1
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    sha1: 58b80c916ad523defea9e661045b7fc700a9ec4f
    url: https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3262.4
    version: 3262.4
- cloud_properties:
    availability_zone: us-west-2b
    instance_type: m3.medium
  name: small_z2
  network: vault_z2
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    sha1: 58b80c916ad523defea9e661045b7fc700a9ec4f
    url: https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3262.4
    version: 3262.4
- cloud_properties:
    availability_zone: us-west-2c
    instance_type: m3.medium
  name: small_z3
  network: vault_z3
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    sha1: 58b80c916ad523defea9e661045b7fc700a9ec4f
    url: https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3262.4
    version: 3262.4
update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 1
  serial: true
  update_watch_time: 1000-60000

